spring.application.name=resume-radar

spring.datasource.url=jdbc:mysql://localhost:3306/Resume_DataBase
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create
// When we move to production later ? we change this to update. Don't forget.
spring.jpa.show-sql=true
