spring.application.name=resume-radar

spring.datasource.url=jdbc:mysql://localhost:3306/Resume_DataBase
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#Shows SQL Query in the console.

security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472JK26250645367566B5420
security.jwt.expiration-time=86400000

# Google Gemini AI API Configuration
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# ACTUATOR - Expose Health Dashboard
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always



